[env]
PKG_CONFIG_PATH = "/opt/homebrew/opt/icu4c/lib/pkgconfig"

[tools]
elixir = "1.18.4-otp-27"
erlang = "28.0"
node = "24.1.0"
postgres = "17.5"
python = "3.13.3"
pre-commit = "4.2.0"
kubectl = "1.33.1"
